---
repository:
  name: gopad-docs
  description: "Gopad: Documentation"
  homepage: https://gopad.eu
  topics: gopad, etherpad, docs, documentation, hugo

  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

...
