baseurl = "/"
languageCode = "en-us"
title = "Gopad"
disableKinds = ["RSS"]

[params]
  Description = "Etherpad for markdown with Go"
  Author = "Gopad Team"
  Website = "https://gopad.webhippie.de"
  Github = "gopad"
