baseurl: /
languageCode: en-us
title: Gopad
disableKinds: RSS

outputs:
  home:
    - html
    - json

params:
  Description: Etherpad for markdown with Go
  Author: Gopad Team
  Website: https://gopad.tech
  Github: gopad
